name: CI Node.js
# Dispara em qualquer push ou pull request, para qualquer branch
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

      # 1. Passo para baixar o código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Passo para configurar o ambiente Node.js na versão desejada
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Passo para instalar as dependências do projeto
      - name: Instalar dependências
        run: npm install

      # 4. Passo para executar a tarefa de teste que configuramos
      - name: Rodar testes
        run: npm test