name: Check for Exposed Credentials

on:
  # push:
  # pull_request:

  push:
    branches: [main] # Roda em commits para a branch 'main'
  pull_request:
    branches: [main] # Roda em Pull Requests direcionados à 'main'

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Baixa o código do repositório.
        with:
          fetch-depth: 0 # Busca o histórico completo do Git para a varredura de segredos.

      - uses: gitleaks/gitleaks-action@v2 # Executa a ferramenta Gitleaks para detecção de segredos.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Fornece um token de acesso para o Gitleaks interagir com o GitHub.